### ISSUE TITLE
Python 2 vs Python 3

### ISSUE THREAD

**Issue by MartinThoma** [sdpython/pyensae#28]
pyensae has some serious Python 2 / Python 3 issues:

* `antlr4`: `from __builtin__ import unicode`, `range` -> Works only in Python 2
* Pyensae can only be installed with Python 3:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c6mwun/pyensae/setup.py", line 110
        raise ImportError(message) from e
                                      ^
    SyntaxError: invalid syntax
```

**Comment by sdpython** [comment]
pyensae does not support python 2, support for python 2 will stop in 2020 (https://pythonclock.org/)

**Comment by MartinThoma** [comment]
Ok, but `antlr4` is a requirement of `pyensae`. And that requirement seems only to work in Python 2.

**Comment by sdpython** [comment]
antlr4 does exist for python 3: https://pypi.org/project/antlr4-python3-runtime/

**Comment by MartinThoma** [comment]
Existing is not the same as working
