### ISSUE TITLE
Cannot run due to import error

### ISSUE THREAD

**Issue by laurentvm** [sdpython/pyensae#32]
Hi, I cannot run your tool as it seems I am missing something but it is not clear what I am missing. I run python3

![image](https://user-images.githubusercontent.com/37613497/71670796-68248680-2d71-11ea-8f1b-2f6bf0e1d241.png)

**Comment by MartinLindh** [comment]
Try to change it to:
 from builtins import unicode

**Comment by sdpython** [comment]
This bug happens in antlr4 not in pyensae. Not sure what I can do here.
