### ISSUE TITLE
Would this work for a R Script with external libraries?

### ISSUE THREAD

**Issue by gabrielpulga** [sdpython/pyensae#42]
Hello, sorry if this has been asked before already.

Would this "convert R script into python code" module work for a R script with external libraries? I suspect it doesn't and that is alright, but I'm looking for something that does - although I'm not sure it exists.

The reason I ask is that my script possess quite a few libs, such as :

```
library(officer)
library(dplyr)
library(tidyr)
library(DatastreamDSWS2R)
library(ggrepel)
library(lubridate)
library(magrittr)
library(data.table)
library(zoo)
library(rvg)
library(aws.s3)
```

**Comment by sdpython** [comment]
No, it won't work. The library only converts a script, not its dependancies.
